### ISSUE TITLE
The case of the disappearing xedit exe

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/XEdit-PACT#5]
For some reason, with current main (not affected by the changes in PR #4) if I tell it to stop cleaning, it will delete my fo4edit.exe also, it seems to use generic xedit mode no matter what instead of using the specific arguments for the game-specific exe names. I think it has something to do with xedit_exc_path, but can't figure out how, or if I'm barking up the wrong tree. It also does the same thing if I run PACT_Start.py from the command line and Ctrl-C out.

**Comment by GuidanceOfGrace** [comment]
Let me know if you're still getting any errors with the new PACT_Start.py. I've tried a bunch of button and settings combinations and cannot replicate it deleting fo4edit.exe, so that's definitely weird...

I had to refactor a couple of things to track down the [WinError 193] error since PyCharm wasn't complaining about anything. This is also now the version with the batch file generation commented out. And the goal is to have INI variables capitalized, to tell them apart from when PACT is checking what's actually running on the PC.

**Comment by evildarkarchon** [comment]
Whatever you did fixed it, replicated my previous scenario as closely as I could remember and my fo4edit.exe remained intact 🙂
When I was poking around the code, both main and my PR branch (to make sure that I didn't cause this myself) I couldn't see wtf was doing it. I'd start, it would kinda go (mo2 complained about too many positional arguments), I'd tell it to stop, boom, fo4edit.exe gone.

**Comment by evildarkarchon** [comment]
btw, there was a line that referenced batdir, which no longer exists. I removed it from my copy, but such a small change doesn't really warrant a PR, it's right after `plugins_processed += 1`

**Comment by GuidanceOfGrace** [comment]
Thanks. I would also assume the whole xedit / bat problem is just the antivirus freaking out over nothing, having a random exe spamming batch files is a big no-no it seems.

**Comment by evildarkarchon** [comment]
Makes sense to me
